### ISSUE TITLE
Log scale when plotting a Graph2D

### ISSUE THREAD

**Issue by pgibertini** [Dessia-tech/plot_data#113]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**

Allow the user to display a log scale when plotting a Graph2D

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** Avoid reference to other packages

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Possible fixes**

* **Please tell us about your environment:**
  
  - branch: 
  - commit:  
  - python version:

**Comment by Jeremie-Ch** [comment]
Done! It works for scatter plots as well
Two parameters "log_scale_x" and "log_scale_y" have been added to classes Scatter and Graph2D
