### ISSUE TITLE
File editing

### ISSUE THREAD

**Issue by Jeremie-Ch** [Dessia-tech/plot_data#126]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** Avoid reference to other packages

* **What is the expected behavior?**
Create a function in standalone mode that writes selected points indices in a txt file.

* **What is the motivation / use case for changing the behavior?**

* **Possible fixes**

* **Please tell us about your environment:**
  
  - branch: 
  - commit:  
  - python version:

**Comment by GhislainJ** [comment]
Current behavior : exports in .txt file the list of selected indices
Expected behavior ? : export json of selected points in .txt file
