### ISSUE TITLE
Save / load configuration

### ISSUE THREAD

**Issue by Jeremie-Ch** [Dessia-tech/plot_data#127]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** Avoid reference to other packages

* **What is the expected behavior?**
Saving / Loading a configuration (coordinates, scaling, selected points, plot types, etc)

* **What is the motivation / use case for changing the behavior?**

* **Possible fixes**

* **Please tell us about your environment:**
  
  - branch: 
  - commit:  
  - python version:

**Comment by GhislainJ** [comment]
Current state : need to check on frontend side with plot-data installed locally
