### ISSUE TITLE
Rotate plot_data.Text

### ISSUE THREAD

**Issue by sbendjebla** [Dessia-tech/plot_data#134]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**

> **plot_data.Text** is always parallel to the x axis

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** Avoid reference to other packages

* **What is the expected behavior?**

> I'm looking for an option for **plot_data.Text** to be able to **_rotate_** it, with a certain angle, and not have it all the time parallel to the x axis. Like in this **photo**
![photo](https://user-images.githubusercontent.com/68638483/150087645-97c1f647-bccf-4f5f-8dcc-a78030ef0ee8.png)

* **What is the motivation / use case for changing the behavior?**

* **Possible fixes**

* **Please tell us about your environment:**
  
  - branch: 
  - commit:  
  - python version:

**Comment by Jeremie-Ch** [comment]
Feature added
