### ISSUE TITLE
Camembert diagrams

### ISSUE THREAD

**Issue by GhislainJ** [Dessia-tech/plot_data#145]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

Implement piecharts 

![image](https://user-images.githubusercontent.com/42537234/155341701-ce641cc3-26be-4870-9aaa-aecf0db31757.png)

**Comment by Tanguylo** [comment]
Splitted into  #170  #171 #172
