### ISSUE TITLE
plot points in primitive group container

### ISSUE THREAD

**Issue by masfaraud** [Dessia-tech/plot_data#164]
I have added a point to primitives of primitives group container but it does not plot
https://github.com/Dessia-tech/plot_data/blob/34198255d03aa5215a1990cab234ee2c1cc86723/script/test_objects/primitive_group_test.py#L21

**Comment by Jeremie-Ch** [comment]
Points are not supported by primitive groups for now, but the feature is coming

**Comment by masfaraud** [comment]
duplicate https://github.com/Dessia-tech/plot_data/issues/90
