### ISSUE TITLE
Arc2D behaving weird 

### ISSUE THREAD

**Issue by AxelRinghausen** [Dessia-tech/plot_data#177]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**
The way the Arc2D behaves when plotted is kind of random.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** Avoid reference to other packages

```
arc = plot_data.Arc2D(0, 0, 1, 0, math.pi)
plot_data.plot_canvas(plot_data.PrimitiveGroup([arc]))
```
We should expect half a circle, but the canvas is empty.

```
arc = plot_data.Arc2D(0, 0, 1, 0.00001, math.pi)
plot_data.plot_canvas(plot_data.PrimitiveGroup([arc]))
```
We should expect (a bit less than) half a circle, but the canvas draws a complete circle. 

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Possible fixes**

* **Please tell us about your environment:**
  
  - plot_data version: 0.8.5 
  - python version: 3.8

**Comment by Tanguylo** [comment]
Fixed in 0.18.0
