### ISSUE TITLE
Tooltip: difficult hovering for plot_data.Wire

### ISSUE THREAD

**Issue by AxelRinghausen** [Dessia-tech/plot_data#182]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**
It is very difficult to display the tooltip for Wire objects because the mouse has to hover the exact pixels of the Wire, being only a couple pixels large. 

* **What is the expected behavior?**
It'd be nice if the hovering was made a bit easier for this object.

* **Please tell us about your environment:**
  
  - branch: master
  - commit: v0.10.1
  - python version: 3.8

**Comment by xavier-ferry** [comment]
Without looking at the code, I can see 2 way of doing this : 

- If, as it was done in the workflowbuilder, getting the arc under the mouse is done via a hidden_canvas, then we just need to draw the arc with a bigger linewidth.
- If not, and this is the right way to do it (look at my pipe handling in the workflowbuilder), we can do it by setting the linewidth when checking if the mouse if over the path : 
```ts      
context.lineWidth = 10
if (context.isPointInStroke(pipe.getPath(), this.mouseMove.x, this.mouseMove.y)) {...}
```
