### ISSUE TITLE
Arc: redundant input data lead to bugs?

### ISSUE THREAD

**Issue by masfaraud** [Dessia-tech/plot_data#191]
* **I'm submitting a ...**
  - [x] bug report

* **What is the current behavior?**
Arc input seems redundant: center, radius, start & end angle, clockwise or not, and even start and end

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** Avoid reference to other packages

There is a script on:
https://github.com/Dessia-tech/plot_data/blob/test_arc/script/arc_test.py
arc should be 345°, it is 15°.
Input are redundant and it is impossible to understand what should be done
is_clackwise is not respected for ex

* **What is the expected behavior?**
Clear input data, non redundant

* **What is the motivation / use case for changing the behavior?**
See script

* **Possible fixes**
* Arc = start, end interior -> computations functions to code in typescript
* matplotlib like input data

* **Please tell us about your environment:**
  
  - branch: master

**Comment by Tanguylo** [comment]
A priori fixed
