### ISSUE TITLE
get more information by hovering over a point in scatter plot

### ISSUE THREAD

**Issue by younesdessia** [Dessia-tech/plot_data#204]
* **I'm submitting a ...**
  - [X] feature request

* **What is the current behavior?**
* 
get more information by hovering over a point in scatterplot, in our case we want to have information from both axes and index of solution.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** Avoid reference to other packages

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Possible fixes**

* **Please tell us about your environment:**
  
  - branch: 
  - commit:  
  - python version:

**Comment by Tanguylo** [comment]
Hi Younès,

Did you try to set a tooltip for your scatter plot ?
If you do the following, I guess you will get what you want :
```
my_data = [DessiaObject] #your data
my_points = [] #what to plot in a scatter
for idx, data in enumerate(my_data):
     my_points.append({'x_param': getattr(data, x_param), 
                       'y_param': getattr(data, y_param),
                       'index': idx})

scatter = Scatter(elements=my_points, tootltip=Tooltip(['x_param', 'y_param', 'index'])
```

**Comment by younesdessia** [comment]
Hi Tanguy,



I did that
![image](https://user-images.githubusercontent.com/109952534/208076160-97e20e75-e38a-4ea5-8032-ab3efb4f18da.png)

I'll try that and let you know, Thanks

**Comment by Tanguylo** [comment]
Yes ! I think it will work.
Don't forget to add i to dict in points ;), like that :
`points.append({'Index': i, 'clearance_engine': ...end of code`
