### ISSUE TITLE
Multiplot : Selected indices is empty when there is a primitives group container

### ISSUE THREAD

**Issue by GhislainJ** [Dessia-tech/plot_data#210]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**

When adding a PrimitivesGroupContainer in order to show 2D displays on a multiplot, selected indices are emitted as empty (`[]`). There even is a log in console that shows it.

This prevent frontend from working properly when investigating workflow results.

This whole section should be refactored anyway

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** Avoid reference to other packages

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Possible fixes**

* **Please tell us about your environment:**
  
  - branch: 
  - commit:  
  - python version:

**Comment by GhislainJ** [comment]
I will check as soon as possible and let you know

**Comment by Tanguylo** [comment]
Can i close this issue ?
