### ISSUE TITLE
Find a way to have dates in axis

### ISSUE THREAD

**Issue by masfaraud** [Dessia-tech/plot_data#211]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**
It is not possible to have date formatting on axis. 

* **What is the expected behavior?**
Matplotlib provides formatters to transform raw data (timestamp) to nice ticks.

* **What is the motivation / use case for changing the behavior?**
Timestamps as dates are unreadable

![image](https://user-images.githubusercontent.com/14061753/210221431-adcc08a0-1380-4ea4-bd88-1dfc257e7689.png)

**Comment by Tanguylo** [comment]
Solved in v0.23.0
