### ISSUE TITLE
Multiplot selection

### ISSUE THREAD

**Issue by younesdessia** [Dessia-tech/plot_data#213]
* **I'm submitting a ...**
  - [X] feature request

* **What is the current behavior?**

When we select a solution in multiplot then we clear, we always have the selected solution.

I don't know if we also need modification in frontend ?

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** Avoid reference to other packages
select solutions in multiplot then clear. 

* **What is the expected behavior?**
no longer have the selected solution

* **What is the motivation / use case for changing the behavior?**

* **Possible fixes**

* **Please tell us about your environment:**
  
  - branch: master
  - commit:  
  - python version: 3.9

![image](https://user-images.githubusercontent.com/109952534/211277514-3cf7dbd4-386d-4fb4-8f91-c763fc4c7305.png)
![image](https://user-images.githubusercontent.com/109952534/211277823-11626b6b-ca13-4877-9d57-c015b5a402e4.png)

**Comment by Tanguylo** [comment]
Hi Younès,
Did you try to click on ctrl key outside a point on any subplot ?

This should reset the whole view of multiplot.
The clear button is one per subplot.

Tell me if you need this behavior to change.

**Comment by Tanguylo** [comment]
Did you try ? Can I close this ticket ?

**Comment by Tanguylo** [comment]
Press ctrl + click
