### ISSUE TITLE
multiplot bug display in platform

### ISSUE THREAD

**Issue by younesdessia** [Dessia-tech/plot_data#219]
* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**
when we are in full screen on the multiplot and we select on the parallel plot (same behavior when on normal screen), we don't get the equivalent on the scatter plot (the reverse too), so once selected we can't deactivate (we have to close the plot to return to the start).

When you leave the full screen, the parallel plot appears behind the scatter, for that we have to close settings and click on order plot.

tell me if need issue in another package.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** Avoid reference to other packages

* **What is the expected behavior?**

when we select on the first axis at the bottom, we get the equivalent on the scatter plot (this is the expected behavior)
![image](https://user-images.githubusercontent.com/109952534/221609945-c374052b-9101-495e-b8f4-630ef231904d.png)

* **What is the motivation / use case for changing the behavior?**

* **Possible fixes**

* **Please tell us about your environment:**
  
  - branch: v0.10.10
  - commit:  
  - python version: platform
  
  
  
![image](https://user-images.githubusercontent.com/109952534/218894452-e4067c1e-9740-4127-9a69-6de332096526.png)
![image](https://user-images.githubusercontent.com/109952534/218894640-44881734-cb3d-4032-a2e7-f644e01bde3e.png)

**Comment by Tanguylo** [comment]
Is this fixed with Cross selection fixes in multiplot ?

**Comment by younesdessia** [comment]
@Tanguylo   I will check today

**Comment by younesdessia** [comment]
@Tanguylo it works fine locally (branch master)
