### ISSUE TITLE
Point positions seems buggy 

### ISSUE THREAD

**Issue by masfaraud** [Dessia-tech/plot_data#233]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**
plot_data 
![image](https://user-images.githubusercontent.com/14061753/222443222-05ecbea9-93a3-41bb-a760-c709d9067e89.png)

matplotlib:

![image](https://user-images.githubusercontent.com/14061753/222443335-2e172a6a-fcd8-4fc8-bfb8-d254cc939f52.png)

reproduced with script/simple_shapes.py

* **What is the expected behavior?**

Similar points positions

* **What is the motivation / use case for changing the behavior?**

* **Possible fixes**

* **Please tell us about your environment:**

  - branch:
  - commit:
  - python version:

**Comment by Tanguylo** [comment]
Solved in v0.18.0
