### ISSUE TITLE
The values ​​on the axes are not good

### ISSUE THREAD

**Issue by younesdessia** [Dessia-tech/plot_data#235]
* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**
on the first axis (bottom) we have an index parameter which has integer values, but on the plot we obtain decimal values.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** Avoid reference to other packages

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Possible fixes**

* **Please tell us about your environment:**

  - branch: master
  - commit: 0.11.0
  - python version:
  
  
![image](https://user-images.githubusercontent.com/109952534/223060067-89618c29-2825-400b-9192-f656d39220af.png)

**Comment by Tanguylo** [comment]
Waiting for ParallelPlot refactor that will be released before the end of september
