### ISSUE TITLE
plot_canvas: In local (debug_mode=True), space into file name create issue in file path for plot-data.js 

### ISSUE THREAD

**Issue by Launayl** [Dessia-tech/plot_data#250]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**
in plot_canvas function,  in local mode(debug_mode=True), space into file name create issue in automatic file path use to find plot-data.js .
The problem is only in Windows because in Linux you can't have space into file.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** Avoid reference to other packages

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Possible fixes**

* **Please tell us about your environment:**

  - branch:
  - commit:
  - python version:

**Comment by Tanguylo** [comment]
Done and tested
