### ISSUE TITLE
Axis names truncated if too long

### ISSUE THREAD

**Issue by BayssetGuillaume** [Dessia-tech/plot_data#261]
* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**
If the axis names are too long they are truncated in the plot data as shown in the picture below:
![image](https://github.com/Dessia-tech/plot_data/assets/107031813/47f36952-9afd-4387-87ea-054d1b515d59)

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** Avoid reference to other packages

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Possible fixes**

* **Please tell us about your environment:**
Plot-data version : 0.12.3
  - branch: 
  - commit: 
  - python version:

**Comment by Tanguylo** [comment]
The vertical behavior is not totally fixed yet but the horizontal one seems to look like your expectations

![image](https://github.com/Dessia-tech/plot_data/assets/106539650/1dc9ea99-be01-4479-af0a-ad0a6557eff6)
