### ISSUE TITLE
bug: parallel plot selection

### ISSUE THREAD

**Issue by younesdessia** [Dessia-tech/plot_data#266]
* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

when we make several selections in the axes of the parallel plot and at the end we move the selection cursor, the number of solutions in the table is not correct (ex: 4 selections, 3 solutions in the table)

![image (1)](https://github.com/Dessia-tech/plot_data/assets/109952534/b031c49f-8b29-4540-a361-2190dccad214)

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** Avoid reference to other packages

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Possible fixes**

* **Please tell us about your environment:**

  - branch: master
  - commit: last 
  - python version:

**Comment by Tanguylo** [comment]
A priori fixed in further release, here: https://github.com/Dessia-tech/plot_data/releases/tag/v0.12.3

**Comment by Tanguylo** [comment]
@NatsuDzn Can it be a bug in frontend ? For example, if frontend is just updating an initial_list instead of creating a new one each time a rubberband changes.

**Comment by NatsuDzn** [comment]
> @NatsuDzn Can it be a bug in frontend ? For example, if frontend is just updating an initial_list instead of creating a new one each time a rubberband changes.

Yes it could be, it might be an issue with the table and not plot_data
