### ISSUE TITLE
Feature: Dynamic graph

### ISSUE THREAD

**Issue by sbendjebla** [Dessia-tech/plot_data#298]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**
In some case, we may have edges that cross like this.

![image](https://github.com/Dessia-tech/plot_data/assets/68638483/524b9b1c-61fd-4502-b3be-9d1664e86e52)

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** Avoid reference to other packages

* **What is the expected behavior?**
I propose two options:
  - generate graph without crossing edges.
  - generate dynamic graph. So, even if the edges are crossing, we can move the nodes as we want to avoid it.

* **What is the motivation / use case for changing the behavior?**

* **Possible fixes**

* **Please tell us about your environment:**

  - branch: master
  - version: 0.15.0
  - python version:

**Comment by Tanguylo** [comment]
This feature has to be specifically developed for each project, with its specifications.

If some features are required for the custom created graph layout to be as expected, then a feature will be developed in plot_data so that it could be used in future graphs.
