### ISSUE TITLE
Blank plot_data displays (Packages Compatibility)

### ISSUE THREAD

**Issue by sbendjebla** [Dessia-tech/plot_data#303]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**
    - We have just blank displays for our different plots.
![image](https://github.com/Dessia-tech/plot_data/assets/68638483/3f6be729-1803-4c2a-8a71-57ce7ab27c2b)

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** Avoid reference to other packages
    - We are using plot_data **V0.16.0** with:
       - dessia_common: **0.13.5.dev626+g79cc81c9**
       - fronted: **master** | **commit: fb112bde**
       - back-end: **master** | **commit: 010dc165**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Possible fixes**

* **Please tell us about your environment:**

  - branch:
  - commit:
  - python version:

**Comment by Tanguylo** [comment]
Hello Soumiya,
Your problem is coming from an incompatibility between the plot-data typescript app and the plot_data python interface.
You should just be sure that the typescript version used by the frontend app is the same as the Python one used by the backend app.

I close this ticket.
