### ISSUE TITLE
Integer-only vectors could have integer-only axis on displays 

### ISSUE THREAD

**Issue by AxelRinghausen** [Dessia-tech/plot_data#307]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**
When a vector is only composed of integers, the axis on the plot shows decimals. 
As shown on the screenshot below, pipe_turns and index_sol are composed of integers, but the axis on both plots shows decimals that are not relevant. 
![image](https://github.com/Dessia-tech/plot_data/assets/50665039/888bcf14-7f95-440f-9c63-d615ded0fe4e)

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** Avoid reference to other packages

* **What is the expected behavior?**
I expect to see only integers displayed on all axis. 

* **What is the motivation / use case for changing the behavior?**
Clarity, use experience

* **Possible fixes**

* **Please tell us about your environment:**
Actually on plot_data  v0.12.6

**Comment by Tanguylo** [comment]
Solved in v0.23.0

**Comment by Tanguylo** [comment]
![image](https://github.com/Dessia-tech/plot_data/assets/106539650/e5936f73-ce7a-486d-94a7-723939fb43bb)

![image](https://github.com/Dessia-tech/plot_data/assets/106539650/42d21b38-6763-43a3-95fc-2da7c2393e0a)

![image](https://github.com/Dessia-tech/plot_data/assets/106539650/66d7e5f9-b7c3-433a-b175-5c9c609d42a4)
