### ISSUE TITLE
Arc2D not working as expected

### ISSUE THREAD

**Issue by GabrielJMS** [Dessia-tech/plot_data#338]
* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**

import plot_data
import math

arc1 = plot_data.Arc2D(0.0, 0.0, 1.0, start_angle=0.0, end_angle=0.5 * math.pi, clockwise=True, edge_style=plot_data.EdgeStyle(color_stroke=plot_data.colors.RED))
arc2 = plot_data.Arc2D(0.0, 0.0, 1.0, start_angle=0.0, end_angle=0.5 * math.pi, clockwise=False, edge_style=plot_data.EdgeStyle(color_stroke=plot_data.colors.BLACK))
primitive_group = plot_data.PrimitiveGroup(primitives=[arc1, arc2])
plot_data.plot_canvas(plot_data_object=primitive_group, debug_mode=True)

![image](https://github.com/Dessia-tech/plot_data/assets/89979482/a0fe4144-2c6a-4849-8686-33c7b540daf7)

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** Avoid reference to other packages

* **What is the expected behavior?**
clockwise parameter should give me the freedom to drawn arc in clockwise direction, but it seems that even with clockwise=True I still need to declare the angles in counterclockwise 
![image](https://github.com/Dessia-tech/plot_data/assets/89979482/3df1f65b-423d-4935-9b63-9a68e92c5575)

* **What is the motivation / use case for changing the behavior?**

* **Possible fixes**

* **Please tell us about your environment:**

  - branch:
  - commit:
  - python version:

**Comment by Tanguylo** [comment]
The angles are absolute i.e. trigonometric angles in absolute frame following this pic:
![image](https://github.com/Dessia-tech/plot_data/assets/106539650/cd166a99-b28e-4b80-8fc3-4d817edbee95)

So, if you need to go clockwise with an increment of Pi/2 from 0, you should write :
`start_angle=0, end_angle=-Pi/2, clockwise=True` or
`start_angle=0, end_angle=3*Pi/2, clockwise=True`
And, if you need to go counter clockwise with an increment of Pi/2 from -Pi/2, you should write :
`start_angle=-Pi/2, end_angle=0, clockwise=False` or 
`start_angle=3*Pi/2, end_angle=0, clockwise=False` or
