### ISSUE TITLE
Text positionning is off

### ISSUE THREAD

**Issue by AxelRinghausen** [Dessia-tech/plot_data#352]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**
The text should appear centered on the cross, but it is slightly below. The selection of the text is at the right spot though. 
![image](https://github.com/Dessia-tech/plot_data/assets/50665039/ac282991-831e-463d-8915-2e23e59731c8)

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** Avoid reference to other packages
```
from plot_data import Text, TextStyle, PrimitiveGroup
from volmdlr import Point2D
from volmdlr.edges import LineSegment2D

text_style = TextStyle(text_color='rgb(0, 0, 0)',
                       font_size=None,
                       text_align_x='center',
                       text_align_y='middle')

text = Text(comment='Hello world!',
            position_x=0.1,
            position_y=0.4,
            text_style=text_style,
            text_scaling=True,
            max_width=0.5,
            multi_lines=False)

ls1 = LineSegment2D(Point2D(0.1, -1), Point2D(0.1, 1)).plot_data()
ls2 = LineSegment2D(Point2D(-1, 0.4), Point2D(1, 0.4)).plot_data()

PrimitiveGroup(primitives=[text, ls1, ls2]).plot()
```

* **What is the expected behavior?**
The text is centered on the cross in this case.

* **What is the motivation / use case for changing the behavior?**

* **Possible fixes**

* **Please tell us about your environment:**

  - branch: master
  - commit: v0.22.0
  - python version: 3.9

**Comment by Tanguylo** [comment]
After a quick investigation, this seems to be a lot of work.

Don't expect it as a patch on v0.22.xx but implemented in the new stable version of June.
