### ISSUE TITLE
Multiplot : Adding a plot and selecting name as a feature messes with selection

### ISSUE THREAD

**Issue by GhislainJ** [Dessia-tech/plot_data#354]
* **I'm submitting a ...**
  - [x] bug report

* **What is the current behavior?**

The following error shows up when doing so

![image](https://github.com/Dessia-tech/plot_data/assets/42537234/8c0eb405-d38d-4cdf-af5c-5204f1404d14)

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
- Create a StandaloneObjectWithDefaultValue
- Open it and show multiplot
- Add a ScatterPlot and select Name as one of the features
- Try and select points

* **What is the expected behavior?**

No error

* **Possible fixes**
Either Name should not give the error or it should not be proposed as one of the available features

* **Please tell us about your environment:**
v0.22.1

**Comment by Tanguylo** [comment]
v0.22.4
