### ISSUE TITLE
Fix/improve html templates

### ISSUE THREAD

**Issue by NatsuDzn** [Dessia-tech/plot_data#373]
* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**

Current template implementation causes prettier (formatter) to "crash".
In the templates, you are using an input of type 'range', but you are closing it. 
Since it's a void element, it shouldn't be closed.

https://developer.mozilla.org/en-US/docs/Glossary/Void_element
  
There is also `&nbsp;` to add spaces but you should use css to add more spacing instead, using flexbox and gap could fix that.

The html files are used in the documentation, and we have a git hook that format the staged files, and it makes the formatter crash that's why I'm making this issue.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** Avoid reference to other packages

- Create an html file
- Try to format it with prettier

* **What is the expected behavior?**

- It should format correctly

* **What is the motivation / use case for changing the behavior?**

- Fix formatting issue when adding templates/html files to the documentation

* **Possible fixes**

- Remove closing input tag

* **Please tell us about your environment:**

  - branch:
  - commit:
  - python version:

**Comment by Tanguylo** [comment]
v0.22.4
