### ISSUE TITLE
Bug: Arc2D mpl_plot

### ISSUE THREAD

**Issue by WirajanDASILVA** [Dessia-tech/plot_data#375]
* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**
![image](https://github.com/Dessia-tech/plot_data/assets/77811165/93b977a3-a6b1-4b00-aace-b03693d4cb1d)

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** Avoid reference to other packages

```
[test_arc2d_plot_data.json](https://github.com/Dessia-tech/plot_data/files/14667400/test_arc2d_plot_data.json)


arc = dessia_common.core.DessiaObject.from_json('..downlodads/test_arc2d_plot_data.json')
ax = arc.plot(edge_style=EdgeStyle('r'))
arc_plot_data = arc.plot_data()
arc_plot_data.mpl_plot()

plot_data.plot_canvas(plot_data_object=plot_data.PrimitiveGroup(primitives=[arc_plot_data]))
```

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Possible fixes**

* **Please tell us about your environment:**

  - branch:
  - commit:
  - python version:

**Comment by Tanguylo** [comment]
Thanks for the dev !

Available in v0.24.0
