### ISSUE TITLE
Disabling highlight option

### ISSUE THREAD

**Issue by masfaraud** [Dessia-tech/plot_data#64]
It seems that for ~ 1000 rectangles (contours) highlight of these is very slow.
Maybe an option to disable it would increase perf

**Comment by Jeremie-Ch** [comment]
What about putting a "highlight" option (default value = True) in Contour2D and Circle2D ?

**Comment by masfaraud** [comment]
yes good idea of implementing it!

**Comment by Jeremie-Ch** [comment]
I trying removing hightlight of contours. Unfortunately it doesn't bring any significant improvement.
