### ISSUE TITLE
Simplify input data: to_disp_attribute_names

### ISSUE THREAD

**Issue by masfaraud** [Dessia-tech/plot_data#65]
To discuss:

* to_disp_attribute_names is an ugly name and should be optionnal? it is used in 2 ways: tooltip and axis. Maybe rename scatter x_axis='attribute1' and y_axis='attribute2'?

![image](https://user-images.githubusercontent.com/14061753/115250285-b3f76c80-a129-11eb-8046-4264f70b4a2c.png)

**Comment by Jeremie-Ch** [comment]
The thing is that Attribute is already a class, so variables that end with "_attribute" are Attribute objects and those who end with "_attribute_name" are strings. 
Also, I have to clearly distinguish the list of displayable attributes on one hand, and the attributes that have to be displayed on a specific plot on the other hand.
But still I'm aware that it's not very elegant and I'll be thinking of it. Meanwhile, any relevant suggestion is welcomed for sure :)

**Comment by GhislainJ** [comment]
New in 0.6.1
