### ISSUE TITLE
turn objects transparent 

### ISSUE THREAD

**Issue by WirajanDASILVA** [Dessia-tech/plot_data#71]
Sometimes there are plots in different planes that superpose each other, and it is often hard to figure out what is happening in the background plane.

What about creating a feature enabling the user to turn the object transparent when he wishes for, so he can have an idea if everything works fine back there? 

![image](https://user-images.githubusercontent.com/77811165/115681231-a114b000-a354-11eb-81bb-b4e8ed0e003d.png)

**Comment by Jeremie-Ch** [comment]
Hi! Actually the feature already exist as you have to set surface_style's opacity to 0. However I made a mistake and it didn't work. I just solved it so you have to wait until the next release!

**Comment by WirajanDASILVA** [comment]
awesome, that's great!! thank you!!
