### ISSUE TITLE
To keep family points when adding Scatterplot

### ISSUE THREAD

**Issue by MackJoly** [Dessia-tech/plot_data#77]
* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**

When user adds Scatterplot with two differents family describe, all points are in the same color and do not take into account theses families.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** Avoid reference to other packages

Add Scatterplot with family describe.

* **What is the expected behavior?**
The user expects to see points in its family color.

* **What is the motivation / use case for changing the behavior?**
It will allow a better identification of specific points

* **Possible fixes**

* **Please tell us about your environment:**
  
  - branch: 
  - commit:  
  - python version:

**Comment by Jeremie-Ch** [comment]
Done!
