### ISSUE TITLE
Parallel plot - rubberband

### ISSUE THREAD

**Issue by MackJoly** [Dessia-tech/plot_data#78]
* **I'm submitting a ...**
  - [ ] bug report
  - [X] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**
When we go to parallelplot rubberband, we can select an interval using percentage of available range.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** Avoid reference to other packages

* **What is the expected behavior?**
User would like to select precisely each interval instead of using percentage that is less accurate.

* **What is the motivation / use case for changing the behavior?**
User specification more accurate.

* **Possible fixes**

* **Please tell us about your environment:**
  
  - branch: 
  - commit:  
  - python version:

**Comment by GhislainJ** [comment]
This has to be frontend side
