### ISSUE TITLE
Remove focus from plot_data

### ISSUE THREAD

**Issue by NatsuDzn** [Dessia-tech/plot_data#83]
* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**

It's not really a bug but when you load an object in the platform you are directly redirected to the canvas

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** Avoid reference to other packages

You only need to load an object on the platform to reproduce this issue

* **What is the expected behavior?**

It is expected to don't have redirection from the library.
From what I saw from the code it was used to read keyboard inputs but it doesn't seem to change anything so it's seems fine to remove it (tried with ctrl + click on point) 

* **What is the motivation / use case for changing the behavior?**

* **Possible fixes**

Just remove this line: https://github.com/Dessia-tech/plot_data/blob/13f9cf541ec3659584a4e689b88c2955d37b5908/src/core.ts#L1490

**Comment by GhislainJ** [comment]
New since 0.6.0
