### ISSUE TITLE
selectionchange event issue

### ISSUE THREAD

**Issue by NatsuDzn** [Dessia-tech/plot_data#97]
* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**

When you create a primitivegroupcontainer, then select multiples points using the selection tool the event is empty instead of returning the indexs of points

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** Avoid reference to other packages

Go to the platform (platform-dev)
Open a workflow run object
Create a primitivegroupcontainer
log event.detail.selected_point_indices inside multi-plot.component.ts (line 124) of the frontend
without a primitivegroupcontainer it returns the index but it's not the case when one already exist 

* **What is the expected behavior?**

It should always return the indexs of points

* **What is the motivation / use case for changing the behavior?**

To fix result component & addDisplay method

**Comment by GhislainJ** [comment]
I think this have been fixed here 79b3669b38815289bc06a4d0a8314b360908aa64
It now works in frontend
